# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from custom_msgs/PoseCtrl.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PoseCtrl(genpy.Message):
  _md5sum = "865803d76e3ad519e963faa7db0e7f17"
  _type = "custom_msgs/PoseCtrl"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Front Left
float64        fl_x
float64        fl_z

# Front Right
float64        fr_x
float64        fr_z

# Front Body
float64        f_pitch
float64        f_delta

# Rear Left
float64        bl_x
float64        bl_z

# Rear Right
float64        br_x
float64        br_z

# Rear Body
float64        b_pitch
float64        b_delta"""
  __slots__ = ['fl_x','fl_z','fr_x','fr_z','f_pitch','f_delta','bl_x','bl_z','br_x','br_z','b_pitch','b_delta']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       fl_x,fl_z,fr_x,fr_z,f_pitch,f_delta,bl_x,bl_z,br_x,br_z,b_pitch,b_delta

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PoseCtrl, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.fl_x is None:
        self.fl_x = 0.
      if self.fl_z is None:
        self.fl_z = 0.
      if self.fr_x is None:
        self.fr_x = 0.
      if self.fr_z is None:
        self.fr_z = 0.
      if self.f_pitch is None:
        self.f_pitch = 0.
      if self.f_delta is None:
        self.f_delta = 0.
      if self.bl_x is None:
        self.bl_x = 0.
      if self.bl_z is None:
        self.bl_z = 0.
      if self.br_x is None:
        self.br_x = 0.
      if self.br_z is None:
        self.br_z = 0.
      if self.b_pitch is None:
        self.b_pitch = 0.
      if self.b_delta is None:
        self.b_delta = 0.
    else:
      self.fl_x = 0.
      self.fl_z = 0.
      self.fr_x = 0.
      self.fr_z = 0.
      self.f_pitch = 0.
      self.f_delta = 0.
      self.bl_x = 0.
      self.bl_z = 0.
      self.br_x = 0.
      self.br_z = 0.
      self.b_pitch = 0.
      self.b_delta = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_12d().pack(_x.fl_x, _x.fl_z, _x.fr_x, _x.fr_z, _x.f_pitch, _x.f_delta, _x.bl_x, _x.bl_z, _x.br_x, _x.br_z, _x.b_pitch, _x.b_delta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 96
      (_x.fl_x, _x.fl_z, _x.fr_x, _x.fr_z, _x.f_pitch, _x.f_delta, _x.bl_x, _x.bl_z, _x.br_x, _x.br_z, _x.b_pitch, _x.b_delta,) = _get_struct_12d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_12d().pack(_x.fl_x, _x.fl_z, _x.fr_x, _x.fr_z, _x.f_pitch, _x.f_delta, _x.bl_x, _x.bl_z, _x.br_x, _x.br_z, _x.b_pitch, _x.b_delta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 96
      (_x.fl_x, _x.fl_z, _x.fr_x, _x.fr_z, _x.f_pitch, _x.f_delta, _x.bl_x, _x.bl_z, _x.br_x, _x.br_z, _x.b_pitch, _x.b_delta,) = _get_struct_12d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_12d = None
def _get_struct_12d():
    global _struct_12d
    if _struct_12d is None:
        _struct_12d = struct.Struct("<12d")
    return _struct_12d
