
classdef PoseCtrl < ros.Message
    %PoseCtrl MATLAB implementation of custom_msgs/PoseCtrl
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'custom_msgs/PoseCtrl' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '865803d76e3ad519e963faa7db0e7f17' % The MD5 Checksum of the message definition
        PropertyList = { 'FlX' 'FlZ' 'FrX' 'FrZ' 'FPitch' 'FDelta' 'BlX' 'BlZ' 'BrX' 'BrZ' 'BPitch' 'BDelta' } % List of non-constant message properties
        ROSPropertyList = { 'fl_x' 'fl_z' 'fr_x' 'fr_z' 'f_pitch' 'f_delta' 'bl_x' 'bl_z' 'br_x' 'br_z' 'b_pitch' 'b_delta' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        FlX
        FlZ
        FrX
        FrZ
        FPitch
        FDelta
        BlX
        BlZ
        BrX
        BrZ
        BPitch
        BDelta
    end
    methods
        function set.FlX(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PoseCtrl', 'FlX');
            obj.FlX = double(val);
        end
        function set.FlZ(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PoseCtrl', 'FlZ');
            obj.FlZ = double(val);
        end
        function set.FrX(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PoseCtrl', 'FrX');
            obj.FrX = double(val);
        end
        function set.FrZ(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PoseCtrl', 'FrZ');
            obj.FrZ = double(val);
        end
        function set.FPitch(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PoseCtrl', 'FPitch');
            obj.FPitch = double(val);
        end
        function set.FDelta(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PoseCtrl', 'FDelta');
            obj.FDelta = double(val);
        end
        function set.BlX(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PoseCtrl', 'BlX');
            obj.BlX = double(val);
        end
        function set.BlZ(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PoseCtrl', 'BlZ');
            obj.BlZ = double(val);
        end
        function set.BrX(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PoseCtrl', 'BrX');
            obj.BrX = double(val);
        end
        function set.BrZ(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PoseCtrl', 'BrZ');
            obj.BrZ = double(val);
        end
        function set.BPitch(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PoseCtrl', 'BPitch');
            obj.BPitch = double(val);
        end
        function set.BDelta(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PoseCtrl', 'BDelta');
            obj.BDelta = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.custom_msgs.PoseCtrl.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.custom_msgs.PoseCtrl(strObj);
        end
    end
end
